server:
  port: 8085
jwt:
  client:
    secret: RdGllrHtJ8uX14xRDXvEtp639OsZjVBwMbZiy
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:auth
    username: sa
    password:
